# Generated by Django 2.2.7 on 2019-11-05 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Char', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='charlist',
            options={'verbose_name': '캐릭터 목록', 'verbose_name_plural': '캐릭터 목록'},
        ),
    ]
