# Generated by Django 2.2.7 on 2019-11-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CharList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charname', models.CharField(max_length=64, verbose_name='캐릭터 이름')),
                ('logcount', models.CharField(max_length=64, verbose_name='로그 수')),
            ],
            options={
                'verbose_name': '캐릭터 순위',
                'verbose_name_plural': '캐릭터 순위',
                'db_table': 'Charanking',
            },
        ),
    ]
