# Generated by Django 2.2.7 on 2019-11-05 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charanking', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CharList',
            new_name='charanking',
        ),
    ]
