# Generated by Django 2.2.7 on 2019-11-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charanking', '0002_auto_20191106_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charanking',
            name='logcount',
            field=models.IntegerField(verbose_name='로그 수'),
        ),
    ]
