# Generated by Django 2.2.7 on 2019-11-11 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogList_game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charname', models.CharField(max_length=64, verbose_name='캐릭터 이름')),
                ('where', models.CharField(max_length=64, verbose_name='장소')),
                ('charcon', models.CharField(max_length=64, verbose_name='콘')),
                ('password', models.CharField(max_length=64, verbose_name='비밀번호')),
                ('contents', models.TextField(verbose_name='내용')),
                ('write_dttm', models.DateTimeField(auto_now_add=True, verbose_name='작성 시간')),
                ('sublog_count', models.IntegerField(verbose_name='서브 로그 개수')),
            ],
            options={
                'verbose_name': '로그_game',
                'verbose_name_plural': '로그_game',
                'db_table': 'LogList_game',
            },
        ),
    ]
