# Generated by Django 2.2.7 on 2019-11-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Log', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loglist',
            name='charcon',
            field=models.CharField(default=1, max_length=64, verbose_name='콘'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loglist',
            name='where',
            field=models.CharField(default=223, max_length=64, verbose_name='장소'),
            preserve_default=False,
        ),
    ]
