# Generated by Django 2.2.7 on 2019-11-05 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Log', '0003_auto_20191105_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='loglist',
            name='sublog_count',
            field=models.IntegerField(default=1, verbose_name='서브 로그 개수'),
            preserve_default=False,
        ),
    ]
